version: '3.8'
services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build:
      context: ./blogger
      dockerfile: Dockerfile.prod
    command: gunicorn blogger.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
volumes:
  static_volume: