# Generated by Django 3.1.2 on 2020-10-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger_app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='total_followed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_read',
            field=models.IntegerField(default=0),
        ),
    ]
